<html><head>	<link rel="shortcut icon" type="image/ico" href="<?php echo base_url();?>/assets/img/favicon.ico" />	<link href="<?php echo base_url();?>/assets/css/style.css" rel="stylesheet" type="text/css" />	<link href="<?php echo base_url();?>/assets/css/main_css.php" rel="stylesheet" type="text/css" />	<link href="<?php echo base_url();?>/assets/css/jquery-ui.css" rel="stylesheet" type="text/css" />	<meta http-equiv="content-type" content="text/html" charset="UTF-8" />	<script src="<?php echo base_url();?>/assets/js/jquery.js"></script>	<script src="<?php echo base_url();?>/assets/js/jquery-ui.js"></script>	<script src="<?php echo base_url();?>/assets/js/jquery.ui.datepicker-es.js"></script>	<script src="<?php echo base_url();?>/assets/js/jquery.agregarcampo.js"></script></head>
<body><?php if(isset($tipo)){	echo '<div><span id="'.$tipo.'">';	echo '<img src="'.base_url().'/assets/img/'.$tipo.'.png" height="15px" width="15px"><strong>'.$mensaje.'</strong>';	echo '</span></div>';}?><?php if(isset($resultados) && $resultados != FALSE){?><h3>Medicamentos y Suplementos hasta el <?php echo $fecha;?></h3><table class="listado">	<thead>		<tr>			<th>Medicamento</th>			<th>Frec. de Consumo</th>			<th>¿Por qué consume el medicamento?</th>			<th>¿Desde cuándo?</th>			<th>Estado</th>			<th>Opciones</th>		</tr>	</thead><?php	foreach ($resultados as $medicamento) {		if ($medicamento->tipo_med == 'Medicamento'){?>	<tbody>		<tr>			<td><?php echo $medicamento->nombre;?></td>
			<td><?php echo ''.$medicamento->valor_frec.' veces ';?>
				<?php echo ($medicamento->tipo_frec=="Diario")?'al d&iacute;a':'por semana';?></td>
			<td><?php echo $medicamento->causa;?></td>
			<td><?php echo $medicamento->fecha_ini;?></td>
			<td><?php echo ($medicamento->status=='Activo')?'S&iacute; Consume':'No Consume';?></td>
			<td>
<a onclick="open('<?php echo site_url()?>/medicamento/detalle_id/<?php echo $medicamento->id;?>','aux','toolbar=NO,location=NO,status=NO,menubar=NO,width=300,height=255')"><img height="24" width="24" src="<?php echo base_url();?>assets/img/detalle.png"></a><!--<a onclick="open('<?php echo site_url()?>/medicamento/modificar_id/<?php echo $medicamento->id;?>','aux','toolbar=NO,location=NO,status=NO,menubar=NO,width=300,height=255')"><img height="24" width="24" src="<?php echo base_url();?>assets/img/modificar.png"></a>--><a href="<?php echo site_url()?>/medicamento/borrar_id/<?php echo $medicamento->id;?>"><img height="24" width="24" src="<?php echo base_url();?>assets/img/borrar.png"></a>
			</td>		
		</tr>
	</tbody>
<?php 	}}?>
</table>
<br>
<br>
<table class="listado">	<thead>		<tr>			<th>Suplemento</th>			<th>Frec. de Consumo</th>			<th>¿Por qué consume el suplemento?</th>			<th>¿Desde cuándo?</th>			<th>Estado</th>			<th>Opciones</th>		</tr>	</thead><?php	foreach ($resultados as $medicamento) {		if ($medicamento->tipo_med == 'Suplemento'){?>	<tbody>		<tr>			<td><?php echo $medicamento->nombre;?></td>			<td><?php echo ''.$medicamento->valor_frec.' veces ';?>				<?php echo ($medicamento->tipo_frec=="Diario")?'al d&iacute;a':'por semana';?></td>			<td><?php echo $medicamento->causa;?></td>			<td><?php echo $medicamento->fecha_ini;?></td>			<td><?php echo ($medicamento->status=='Activo')?'S&iacute; Consume':'No Consume';?></td>			<td><a onclick="open('<?php echo site_url()?>/medicamento/detalle_id/<?php echo $medicamento->id;?>','aux','toolbar=NO,location=NO,status=NO,menubar=NO,width=300,height=255')"><img height="24" width="24" src="<?php echo base_url();?>assets/img/detalle.png"></a><!--<a onclick="open('<?php echo site_url()?>/medicamento/modificar_id/<?php echo $medicamento->id;?>','aux','toolbar=NO,location=NO,status=NO,menubar=NO,width=300,height=255')"><img height="24" width="24" src="<?php echo base_url();?>assets/img/modificar.png"></a>--><a href="<?php echo site_url()?>/medicamento/borrar_id/<?php echo $medicamento->id;?>"><img height="24" width="24" src="<?php echo base_url();?>assets/img/borrar.png"></a>			</td>			</tr>	</tbody><?php }}?></table><?php }?></body></html>